vsim -do "do ../scripts/sim.do all 0 0"
vsim -do "do ../scripts/sim.do all 1 0"
vsim -do "do ../scripts/sim.do all 2 0"
vsim -do "do ../scripts/sim.do all 3 0"
vsim -do "do ../scripts/sim.do all 4 0"
vsim -do "do ../scripts/sim.do all 5 0"
vsim -do "do ../scripts/sim.do all 6 0"
