vsim -c -do "do ../scripts/sim.do"
vsim -c -do "do ../scripts/sim.do all 1"
vsim -c -do "do ../scripts/sim.do all 2"
vsim -c -do "do ../scripts/sim.do all 3"
vsim -c -do "do ../scripts/sim.do all 4"
vsim -c -do "do ../scripts/sim.do all 5"
vsim -c -do "do ../scripts/sim.do all 6"
vsim -c -do "do ../scripts/sim.do all 7"
